version: "3"

services:
  app:
    build:
      context: ./go
      dockerfile: Dockerfile
    container_name: app
    env_file:
      - .env
    ports:
      - 4000:4000
    expose:
      - 4000
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    env_file:
      - .env
    depends_on:
      - app
    ports:
      - 8000:8000
    expose:
      - 8000
    restart: unless-stopped
    network_mode: host

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 5000:80
    depends_on:
      - app
      - api
